buildscript {
    ext {
        compileSdkVersion = 33
        targetSdkVersion = 33
        minSdkVersion = 21
        kotlinVersion = "1.8.20"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.4.2")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
        // no react-native-gradle-plugin here
    }
}
