# Project-wide Gradle settings

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true

# Architectures for building APKs
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Enable new architecture features like TurboModules/Fabric
newArchEnabled=true

# Use Hermes JS engine (faster than JSC, recommended)
hermesEnabled=true

# Enable Flipper's network inspector for development
EX_DEV_CLIENT_NETWORK_INSPECTOR=true
android.suppressUnsupportedCompileSdk=34,35


