platform :ios, '13.0' # or whatever iOS version you want to support

require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'reactnativepmt' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true, # or false if you use JSC
    :fabric_enabled => true  # only if you're using the new architecture
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end
